name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest
    outputs:
      source_path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files for Debug
        run: ls -la

      # Optionally, upload the source as an artifact so other jobs can use it
      - name: Upload Source Artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .
  
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Download Source Artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AWS ECR
        env:
          AWS_REGION: ca-central-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          echo "Logging into AWS ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t more_final .

      - name: Tag Docker Image
        env:
          AWS_REGION: ca-central-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          echo "Tagging Docker image..."
          docker tag more_final:latest $AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/more-final-api:latest

      - name: Push Docker Image to ECR
        env:
          AWS_REGION: ca-central-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          echo "Pushing Docker image to ECR..."
          docker push $AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/more-final-api:latest

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Source Artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Checkout Repository (Alternative to download artifact)
        # If you prefer to simply check out the repo again, you can use the checkout action:
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.11"  # Update as needed

      - name: Terraform Validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ca-central-1"
        run: terraform validate

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ca-central-1"
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ca-central-1"
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ca-central-1"
        run: terraform apply -auto-approve tfplan
